name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: ${{ github.event_name == 'workflow_dispatch' }}
          secrets: |
            TWITCH_ID
            TWITCH_SECRET
            RESTREAM_ID
            RESTREAM_SECRET
        env:
          TWITCH_ID: ${{ secrets.TWITCH_ID }}
          TWITCH_SECRET: ${{ secrets.TWITCH_SECRET }}
          RESTREAM_ID: ${{ secrets.RESTREAM_ID }}
          RESTREAM_SECRET: ${{ secrets.RESTREAM_SECRET }}
