name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      update_secrets:
        description: 'Push secrets to cloudflare'
        type: boolean
        required: false
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Install wrangler
        run: cargo install wrangler

      - name: Build
        if: github.event_name != 'workflow_dispatch'
        run: wrangler build

      - name: Publish
        if: github.event_name == 'workflow_dispatch'
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Publish secrets
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.update_secrets == 'true'
        run: |
            echo '${{ secrets.TWITCH_ID }}' | wrangler secret put "TWITCH_ID"
            echo '${{ secrets.TWITCH_SECRET }}' | wrangler secret put "TWITCH_SECRET"
            echo '${{ secrets.RESTREAM_ID }}' | wrangler secret put "RESTREAM_ID"
            echo '${{ secrets.RESTREAM_SECRET }}' | wrangler secret put "RESTREAM_SECRET"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
